### ISSUE TITLE
Beeps Light but no rebbot

### ISSUE THREAD

**Issue by Djang0Pepper** [danieleborgo/OctoPrint-ShutdownButtonLEDBuzzer#10] opened 2022-02-10 11:24 UTC
Installed on pi4 with octoprint
sound like a charm at boot but When button is pushed beeps go on, but no shutdown. 

I try to change this line : 
` PI_SHUTDOWN_COMMAND = "shutdown -h now" `
with
` PI_SHUTDOWN_COMMAND = "sudo shutdown -h now" `
in : "~/oprint/lib/python3.7/site-packages/octoprint_shutdownbuttonledbuzzer/__init__.py"

can you help me ?

**Comment by Djang0Pepper** [comment] 2022-02-10 11:28
forget to reboot It's working now like a charm. regards

**Comment by slepiavka** [comment] 2022-02-21 08:36
Hi, I'm experiencing the same error. I just did a fresh re-install a couple days ago, and the LED and buzzer work fine.

The button, however, doesn't behave as intended. Once Octoprint is running, the plugin does register the press (buzzer beeps), but nothing else happens. If I press it again, the buzzer won't beep (the "button" is just a jumper cable).

Shutting down via GUI or `sudo shutdown now` via SSH works well and the buzzer beeps before shutdown.

If I run a non-sudo command via SSH, it naturally fails, **which I think is related to the issue in question**:
```
pi@octopi:/var/log $ shutdown now
Failed to set wall message, ignoring: Interactive authentication required.
Failed to power off system via logind: Interactive authentication required.
Failed to open initctl fifo: Permission denied
Failed to talk to init daemon.
```

Couldn't find plugin-specific logs, so here's all the logs related to the plugin after boot and when pressing the button:
 ```
|  ShutdownButtonLEDBuzzer (0.1.3) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_shutdownbuttonledbuzzer
2022-02-21 00:26:13,817 - octoprint.plugins.shutdownbuttonledbuzzer - INFO - Plugin ready
2022-02-21 00:26:14,264 - octoprint.plugins.tracking - INFO - Sent tracking event pong, payload: {'version': '1.7.3', 'os': 'linux', 'bits': 32, 'python': '3.7.3', 'pip': '20.3.3', 'cores': 4, 'freq': 1500.0, 'ram': 1903980544, 'pi_model': 'Raspberry Pi 4 Model B Rev 1.1', 'octopi_version': '0.18.0', 'plugins': 'thespaghettidetective:1.8.10,shutdownbuttonledbuzzer:0.1.3,preheat:0.8.0,resource_monitor:0.3.6,psucontrol:1.0.6,psucontrol_homeassistant:1.0.4,printtimegenius:2.2.8,fullscreen:0.0.6,filamentmanager:1.9.1,camerasettings:0.3.1,octolapse:0.4.1,ender3v2tempfix:0.0.4,bedlevelvisualizer:1.1.1'}
2022-02-21 00:27:15,414 - octoprint.plugins.shutdownbuttonledbuzzer - INFO - Refresh request received
2022-02-21 00:27:28,011 - octoprint.plugins.shutdownbuttonledbuzzer - INFO - Shutdown command received
```
If I press it again, there's a logged event, but no beep:
`2022-02-21 00:29:45,846 - octoprint.plugins.shutdownbuttonledbuzzer - INFO - Refresh request received`

Hope this is useful.

**Comment by danieleborgo** [comment] 2022-02-22 23:00
Hi @slepiavka,
this problem should be fixed with the merge I did today. Could you try to uninstall and install again the plugin?

**Comment by slepiavka** [comment] 2022-02-23 18:56
Works like a charm, you did it again!

**Closed** 2022-02-23 22:36 UTC
